spring:
  application:
    name: gateway
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://47.107.111.6:8761/eureka
    enabled: true

zuul:
  routes:
    api-a:
      path: /api/user/**
      serviceId: PERSONNEL-MANAGE
    api-b:
      path: /api/file/**
      serviceId: file-manage
